export { default as Navbar } from './Navbar/Navbar';
export { default as ScheduleCallForm } from './ScheduleCallForm/ScheduleCallForm';
export { default as Services } from './Services/Services';
export { default as BrandsSlider  } from './BrandsSlider/BrandsSlider';
export { default as Testimonials } from './Testimonials/Testimonials';
export { default as CreatePost } from './admin/ManageBlog/CreatePost/CreatePost';
export { default as Blog } from './Blog/Blog';
export { default as ManageTestimonials } from '../components/admin/ManageTestimonials/ManageTestimonials';
export { default as ManageBlog } from '../components/admin/ManageBlog/ManageBlog';